pool:
    vmImage: 'Ubuntu-16.04'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.7'
    architecture: 'x64'

- script: pip install --upgrade pip && pip install -r requirements.txt
  displayName: 'Install requirements'

- script: pytest 
  displayName: 'Run test'

- script: python setup.py sdist bdist_wheel
  displayName: 'Build python package'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: './dist'
    ArtifactName: 'pyot'
  displayName: 'Publish python package'

- task: AzureKeyVault@1
  inputs:
    azureSubscription: 'masota-cseazure(6e3d5121-9b76-4db1-9f55-877904ca127e)'
    KeyVaultName: 'dataops-kv'
    SecretsFilter: '*'
    RunAsPreJob: false

- script: echo $(ado-test-string) > secret-test.txt
- publish: secret-test.txt